### ISSUE TITLE
Add coin sample to default install of Fusebot

### ISSUE THREAD

**Issue by yavorg** [fusebit/fusebot#22]
Let's give users something useful to do beyond the base case of a hello-world.

We can add /fusebot coin as a command that just comes with Fusebot out of the box.

We can also allow users to edit and rm the coin command unlike the other build-in commands.

https://github.com/fusebit/fusebot/tree/main/samples/coin

Once this is available, I will adjust the callback instructions to run and review this code instead of hello-world.

**Comment by yavorg** [comment]
Perhaps can be solved in the way suggested by #14?

**Comment by tjanczuk** [comment]
Every Slack or Discord team will now get a `coin` command automatically added to its space on installation. It can be run with `/fusebot coin doge`. 

If a team re-installs Fusebot and the `coin` command already exists, it is left intact.
